import * as THREE from "three";

import {
  HOME_HEIGHT,
  HOME_POINTS,
  HOME_PROPS,
  HOME_WIDTH
} from "../../levels/homeIntroLevel.js";
import { TILE } from "../../config/constants.js";
import { sceneGridPoint } from "../../core/grid.js";
import {
  addGridPlane,
  addSceneGridTile,
  createBoxMarker,
  createDiscMarker,
  createReadOnlyBounds,
  EDITOR_SURFACE_Y,
  makeObjectColliderProxies,
  setPointPosition,
  sourceRef,
  tagEditorRoot
} from "./editorLevelUtils.js";

const LEVEL_ID = "home_intro";
const SOURCE_FILE = "src/levels/homeIntroLevel.js";

function addHomeTrail({ group, cloneAsset, editableObjects }) {
  for (let x = 0; x < HOME_WIDTH; x += 1) {
    addSceneGridTile({
      group,
      cloneAsset,
      width: HOME_WIDTH,
      height: HOME_HEIGHT,
      x,
      y: 5,
      assetKey: "pathTile",
      editableObjects,
      id: `home_intro.terrain.path.${x}.5`,
      name: `Home Trail Tile ${x},5`,
      sourceRef: sourceRef(SOURCE_FILE, "HOME_WIDTH", `generated-trail:${x},5`, {
        generated: true,
        note: "Home trail tile is generated by the editor preview from runtime trail layout."
      })
    });
  }
  [
    [5, 4],
    [6, 4],
    [7, 4]
  ].forEach(([x, y]) => {
    addSceneGridTile({
      group,
      cloneAsset,
      width: HOME_WIDTH,
      height: HOME_HEIGHT,
      x,
      y,
      assetKey: "pathTile",
      editableObjects,
      id: `home_intro.terrain.path.${x}.${y}`,
      name: `Home Trail Tile ${x},${y}`,
      sourceRef: sourceRef(SOURCE_FILE, "HOME_WIDTH", `generated-trail:${x},${y}`, {
        generated: true,
        note: "Home trail tile is generated by the editor preview from runtime trail layout."
      })
    });
  });
}

export function buildHomeIntroEditorScene({ cloneAsset, placeAsset }) {
  const group = new THREE.Group();
  group.name = "Home Intro Editor Scene";
  const editableObjects = [];

  addGridPlane({
    group,
    cloneAsset,
    width: HOME_WIDTH,
    height: HOME_HEIGHT,
    editableObjects,
    idPrefix: "home_intro.terrain.ground",
    namePrefix: "Home Ground Tile",
    sourceRefForTile: ({ x, y }) => sourceRef(SOURCE_FILE, "HOME_WIDTH", `generated-ground:${x},${y}`, {
      generated: true,
      note: "Home ground tile is generated from HOME_WIDTH and HOME_HEIGHT."
    })
  });
  addHomeTrail({ group, cloneAsset, editableObjects });

  const house = placeAsset(group, "homeBlue", HOME_POINTS.house, {
    y: EDITOR_SURFACE_Y,
    rotationY: Math.PI,
    scale: 1
  });
  editableObjects.push(tagEditorRoot(house, {
    id: "home_intro.house",
    name: "Home House",
    category: "landmark",
    assetKey: "homeBlue",
    sourceRef: sourceRef(SOURCE_FILE, "HOME_POINTS", "house")
  }));

  const doorNote = createBoxMarker({
    name: "Door Note Marker",
    color: 0xffe0a3,
    size: [0.62, 0.12, 0.46],
    opacity: 0.9
  });
  setPointPosition(doorNote, HOME_POINTS.note, EDITOR_SURFACE_Y + 0.09);
  group.add(doorNote);
  editableObjects.push(tagEditorRoot(doorNote, {
    id: "home_intro.door_note",
    name: "Door Note",
    category: "story_note",
    assetKey: "generated-note-marker",
    sourceRef: sourceRef(SOURCE_FILE, "HOME_POINTS", "note", {
      generated: true,
      note: "Runtime creates the note marker; source position is HOME_POINTS.note."
    })
  }));

  const exitMarker = createDiscMarker({ name: "Exit Marker", color: 0x8ed1fc, radius: 0.62 });
  setPointPosition(exitMarker, HOME_POINTS.exit, EDITOR_SURFACE_Y + 0.06);
  group.add(exitMarker);
  editableObjects.push(tagEditorRoot(exitMarker, {
    id: "home_intro.exit_marker",
    name: "Exit Marker",
    category: "exit",
    assetKey: "generated-exit-marker",
    sourceRef: sourceRef(SOURCE_FILE, "HOME_POINTS", "exit", {
      generated: true,
      note: "Runtime uses this point as an exit trigger marker."
    })
  }));

  HOME_PROPS.forEach(([assetKey, x, y, scale], index) => {
    const point = sceneGridPoint(HOME_WIDTH, HOME_HEIGHT, x, y, TILE);
    const prop = placeAsset(group, assetKey, point, {
      y: EDITOR_SURFACE_Y,
      rotationY: index * 0.48,
      scale
    });
    editableObjects.push(tagEditorRoot(prop, {
      id: `home_intro.prop.${assetKey}.${index + 1}`,
      name: `${assetKey} ${index + 1}`,
      category: "prop",
      assetKey,
      sourceRef: sourceRef(SOURCE_FILE, "HOME_PROPS", `[${index}]`)
    }));
  });

  group.add(createReadOnlyBounds(HOME_WIDTH, HOME_HEIGHT, 0x8bc4ff));

  return {
    id: LEVEL_ID,
    name: "Home Intro",
    group,
    editableObjects,
    colliderProxies: makeObjectColliderProxies(editableObjects)
  };
}

export const levelEditorAdapter = {
  id: LEVEL_ID,
  name: "Home Intro",
  order: 20,
  playDebugScene: LEVEL_ID,
  defaultSelectedId: "home_intro.house",
  buildEditorScene: buildHomeIntroEditorScene
};
